### ISSUE TITLE
bypass graphql endpoint

### ISSUE THREAD

**Issue by rotten** [rochacbruno/flasgger#153]
I've injected a GraphQL endpoint into my otherwise Flask based REST API (using Graphene).

Unfortunately this breaks the flasgger swagger ui:
`AttributeError: type object 'GraphQLView' has no attribute 'get'
`
Because of the nature of GraphQL endpoints, I don't really need a Swagger doc for it.

I set up the new endpoint like this:
```
app.add_url_rule('/v2/path/to/graphql',
                 endpoint='my_graphql_endpoint',
                 view_func=GraphQLView.as_view('my_graphql_endpoint', schema=SomeSchemaClass, graphiql=True))
```

I'd like to be able to tell flasgger that it should just ignore this endpoint.  Or, it is welcome to make a note of it, but at least not try to parse it like an ordinary old fashioned REST endpoint.   It is not obvious from the documentation how to do this.

**Comment by rotten** [comment]
Doing this at the top of the file - and then changing the **view_func** - seemed to work, but only because it doesn't look like these functions already existed in GraphQLView:

```
from flask_graphql  import GraphQLView

class myGraphQLView(GraphQLView):
    def get():
        pass
    def post():
        pass
    def delete():
        pass
    def put():
        pass
```

Is that really the best approach?

**Comment by rochacbruno** [comment]
@rotten looks like a bug, flasgger should ignore non `swaggable` endpoints. I'll take a look

**Comment by rochacbruno** [comment]
@rotten can you tell me esact traceback message?

Which lines generated the `AttributeError: type object 'GraphQLView' has no attribute 'get'` ?

**Comment by rotten** [comment]
Here's the full stack:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/local/lib/python3.5/dist-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/local/lib/python3.5/dist-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flasgger/base.py", line 187, in get
    optional_fields, self.process_doc)
  File "/usr/local/lib/python3.5/dist-packages/flasgger/utils.py", line 65, in get_specs
    methods[verb] = getattr(endpoint.view_class, verb)
AttributeError: type object 'GraphQLView' has no attribute 'get'

```
