### ISSUE TITLE
Runtime error when using definitions with marshmallow

### ISSUE THREAD

**Issue by motsu35** [rochacbruno/flasgger#236]
Im not sure the best way to describe the issue, so ill give a bit of working code, and then what you need to do to reproduce the error:
```python
from flask import Flask, jsonify, request
from flask_restful import Resource, Api
from flasgger import Schema, Swagger, SwaggerView, fields
app = Flask(__name__)

app.config['SWAGGER'] = {
	'title': 'sample app for github issue'
}

swagger = Swagger(app)
api = Api(app)

class bar(Schema):
	a = fields.Str()
	b = fields.Dict()
	c = fields.Str()

class foo(Schema):
	JobFoo = fields.Str()

class api_foo(SwaggerView):
	definitions = {
		'bar' : bar,
		'foo' : foo,
	}
	
	def get(self):
		return "hello root!", 200

api.add_resource(api_foo, '/jobs/')

if __name__ == '__main__':
  app.run()
```

this should work fine if you go to the /apidocs/ url. you should see both foo and bar under models.

now, go back and change the class definition of bar to be 'class bar2(Schema)' and update the definitions object

```python
class bar2(Schema):
	a = fields.Str()
	b = fields.Dict()
	c = fields.Str()
...
class api_foo(SwaggerView):
	definitions = {
		'bar' : bar2,
		'foo' : foo,
	}
    ...
```

you will now get an error about the dictionary changing size during iteration
```
[2018-09-06 17:52:24,477] ERROR in app: Exception on /apispec_1.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flasgger/base.py", line 204, in get
    optional_fields, self.process_doc)
  File "/usr/local/lib/python3.6/dist-packages/flasgger/utils.py", line 126, in get_specs
    convert_schemas(apispec_swag, apispec_definitions)
  File "/usr/local/lib/python3.6/dist-packages/flasgger/marshmallow_apispec.py", line 101, in convert_schemas
    v = convert_schemas(v, definitions)
  File "/usr/local/lib/python3.6/dist-packages/flasgger/marshmallow_apispec.py", line 99, in convert_schemas
    for k, v in d.items():
RuntimeError: dictionary changed size during iteration
127.0.0.1 - - [06/Sep/2018 17:52:24] "GET /apispec_1.json HTTP/1.1" 500 -
```

A few times the error did not happen with different length class names, but i was not able to reproduce this reliably (it just happened once when i was trying to test for this issue). It seems that specifying a definitions structure and then using the $ref in the doc string is the only way to get marshmallow definitions at the get/post/put level (instead of defining in native python objects like in [this example](https://github.com/rochacbruno/flasgger/blob/master/examples/colors_with_schema.py)).

**Comment by motsu35** [comment]
doing a bit more digging, it seems like the root cause is when the string in the dictionary does not match up with the name of the class

**Comment by Parvez-Khan-1** [comment]
I am facing the same issue, did you got solution?

**Comment by ongopongo** [comment]
>the [...] cause is when the string in the dictionary does not match up with the name of the class

Thank you for sharing this finding, @motsu35! 🙌 

I was trying to use a SwaggerView for the first time, yesterday, and ran into this same issue.

In my case, I use dynamically-generated Marshmallow schema classes, each of which has a dynamically-generated class name. None of those class names happened to matched their respective keys of the `definitions` object (I wasn't aware that was a requirement until I saw your comment), so I was getting the `RuntimeError: dictionary changed size during iteration` error.

Here's how I ended up working around it.

I ended up implementing a `rename_class` helper function that [renames the class](https://stackoverflow.com/a/54284495) passed in, by setting these attributes of the class:

```py
class_passed_in.__name__     = new_name_of_class
class_passed_in.__qualname__ = new_name_of_class
```

Then, I used that helper function to update the dynamically-generated Marshmallow schema classes so that they have names that are under my control (e.g. `rename_class(DynamicallyGeneratedMarshmallowSchemaClass, "UserSchema")`). My `definitions` dictionary ended up looking something like this:

```py
# Note: Despite the _variable_ still being named `DynamicallyGeneratedMarshmallowSchemaClass`, the referenced class has the name `UserSchema` at this point
definitions = dict(UserSchema=DynamicallyGeneratedMarshmallowSchemaClass)
```

Finally, I referenced the `definitions` key in my docstring YAML. For example:

```yaml
        responses:
            200:
                description: A `User`
                schema: { $ref: '#/definitions/UserSchema' }
```
