### ISSUE TITLE
@swag_from("relative_path.yml") throws ImportError: No module named 'home' when using venv environments

### ISSUE THREAD

**Issue by jkgeyti** [rochacbruno/flasgger#252]
EDIT: SCRATCH THAT. This was an unfortunate side effect of mixing up `-` and `_` in file names. Flasgger couldn't find the file, and then tried to import it as a module, which worked with importlib due to _ and - import rules. There's still a problem in using imp, but I just hit an unfortunate corner case, so I'm closing this :)

Visiting http://127.0.0.1:5050/apidocs/ throws the following exception when using `@swag_from("test-relative_path.yml", validation=True)`

`imp.find_module` is deprecated since python 3.4, and can be replaced by `import_module.find_module`.

```
Traceback (most recent call last):
  File "./lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "./lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "./lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "./lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "./lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "./lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "./lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "./lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "./lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "./lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "./lib/python3.6/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "./lib/python3.6/site-packages/flasgger/base.py", line 108, in get
    return jsonify(self.loader())
  File "./lib/python3.6/site-packages/flasgger/base.py", line 331, in get_apispecs
    doc_dir=self.config.get('doc_dir'))
  File "./lib/python3.6/site-packages/flasgger/utils.py", line 146, in get_specs
    method, sanitizer, endpoint=rule.endpoint, verb=verb)
  File "./lib/python3.6/site-packages/flasgger/utils.py", line 522, in parse_docstring
    full_doc = load_from_file(swag_path, swag_type)
  File "./lib/python3.6/site-packages/flasgger/utils.py", line 490, in load_from_file
    site_package = imp.find_module(path[0])[1]
  File "/usr/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'home'
```

**Comment by javabrett** [comment]
Should this issue be closed?

**Comment by rochacbruno** [comment]
@javabrett do you think `"test-relative_path.yml"` should be a a supported path? I have not tested yet

**Comment by javabrett** [comment]
I have not yet tested either, but read the edit:

> There's still a problem in using imp, but I just hit an unfortunate corner case, so I'm closing this :)

... and wondered whether this was now solved/defunct and a new issue required for any issues specific to `imp`.  @jkgeyti .

**Comment by jkgeyti** [comment]
I believe it all works as intended. I just ran into a corner case where I could get a misspelled path to work with importlib due to pythons handling of dashes and underscores. 

This issue and pr is way too confusing now, so while imp should still be replaced, don’t do it on the back of this ticket. 

Closing
