### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by Parvez-Khan-1** [rochacbruno/flasgger#269]
from flask import Flask, jsonify, request
from flasgger import Swagger, SwaggerView
from marshmallow import Schema, fields

StudentData = {
    1: {"name": "A", 'roll': 1, 'status': 'Pass'},
    2: {"name": "B", 'roll': 2, 'status': 'Pass'},
    3: {"name": "C", 'roll': 3, 'status': 'Pass'},
    4: {"name": "D", 'roll': 4, 'status': 'Pass'},
    5: {"name": "E", 'roll': 5, 'status': 'Pass'}
}

class Student(Schema):
    roll = fields.Integer(required=True)

class StudentDetails(Schema):
    name = fields.Str()
    roll = fields.Str()
    status = fields.Str()

class StudentView(SwaggerView):
    definitions = {'Input': Student, 'Response': StudentDetails}

    def post(self):
        '''
            parameters:
                schema:
                    $ref: '#/definitions/Input'
            responses:
                200:
                    schema:
                        $ref: '#/definitions/Response'
        '''
        request_data = request.json
        roll = request_data.get('roll')
        if roll in StudentData.keys():
            return jsonify(StudentData[roll])
        else:
            return jsonify("Sorry No Record Found...!")

app = Flask(__name__)
swagger = Swagger(app)

app.add_url_rule(
    '/student',
    view_func=StudentView.as_view('student'),
    methods=['POST']
)

app.run(debug=True)

The above is my sample code, when I am executing this I am facing an issue as mention below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flasgger/base.py", line 125, in get
    return jsonify(self.loader())
  File "/usr/local/lib/python3.5/dist-packages/flasgger/base.py", line 348, in get_apispecs
    doc_dir=self.config.get('doc_dir'))
  File "/usr/local/lib/python3.5/dist-packages/flasgger/utils.py", line 126, in get_specs
    convert_schemas(apispec_swag, apispec_definitions)
  File "/usr/local/lib/python3.5/dist-packages/flasgger/marshmallow_apispec.py", line 101, in convert_schemas
    v = convert_schemas(v, definitions)
  File "/usr/local/lib/python3.5/dist-packages/flasgger/marshmallow_apispec.py", line 99, in convert_schemas
    for k, v in d.items():
**RuntimeError: dictionary changed size during iteration**

**Comment by javabrett** [comment]
Duplicates #236.
