### ISSUE TITLE
 __init__() missing 2 required positional arguments: 'schema_name_resolver' and 'spec'

### ISSUE THREAD

**Issue by wobeng** [rochacbruno/flasgger#285]
Hello, I'm getting the error below. Am I missing anything?

```
../../../env36/lib64/python3.6/site-packages/flask_base/app.py:1: in <module>
    from flasgger import Swagger, LazyString, LazyJSONEncoder
../../../env36/lib64/python3.6/site-packages/flasgger/__init__.py:8: in <module>
    from .base import Swagger, Flasgger, NO_SANITIZER, BR_SANITIZER, MK_SANITIZER, LazyJSONEncoder  # noqa
../../../env36/lib64/python3.6/site-packages/flasgger/base.py:37: in <module>
    from .utils import extract_definitions
../../../env36/lib64/python3.6/site-packages/flasgger/utils.py:22: in <module>
    from .marshmallow_apispec import SwaggerView
../../../env36/lib64/python3.6/site-packages/flasgger/marshmallow_apispec.py:13: in <module>
    openapi_converter = openapi.OpenAPIConverter(openapi_version='2.0')
E   TypeError: __init__() missing 2 required positional arguments: 'schema_name_resolver' and 'spec'
```

**Comment by wangsha** [comment]
latest version of apispec has breaking changes. pin it to version 1.0.0b5

**Comment by quaterneon** [comment]
If you depend on the apispec marshmallow extension, the above suggestion of pinning to 1.0.0b5 won't work.

**Comment by wangsha** [comment]
@quaterneon what's the error you get?

**Comment by pgalilea** [comment]
Same error here, with just
from flasgger import Swagger

**Comment by dhughesni** [comment]
_I have identified the same error, although I was unable to trace the exact change in either module: apispec or marshmallow._

## Investigation

The error reports in flasgger: 
```
../../../env36/lib64/python3.6/site-packages/flasgger/marshmallow_apispec.py:13: in <module>
    openapi_converter = openapi.OpenAPIConverter(openapi_version='2.0')
E   TypeError: __init__() missing 2 required positional arguments: 'schema_name_resolver' and 'spec'
```
The file was last changed **8 months ago** with *54d9e77  on 29 Jun 2018*: https://github.com/rochacbruno/flasgger/blob/master/flasgger/marshmallow_apispec.py

The file imports the following:
```from apispec.ext.marshmallow import openapi```

Which leads us to: https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/openapi.py#L107
After reviewing the commits, it seems the following changes may have resulted in the error in flasgger:
- https://github.com/marshmallow-code/apispec/commit/35287af6398fb34c77f387a24b114b78320c0d57#diff-462f583a2475d6692f0826c94b8dc686
- https://github.com/marshmallow-code/apispec/commit/6f6c6b7bfa0054228c191fa626d6c59642ed367c#diff-462f583a2475d6692f0826c94b8dc686
- https://github.com/marshmallow-code/apispec/commit/98a9c402a8208e95c86c340e49281049dda1b3c9#diff-462f583a2475d6692f0826c94b8dc686

## The fix to flasgger 
https://github.com/rochacbruno/flasgger/blob/master/flasgger/marshmallow_apispec.py#L13
```
openapi_converter = openapi.OpenAPIConverter(
    openapi_version="2.0", 
    schema_name_resolver=None, 
    spec=None
)
```
_This change enables the code to run, but I am not aware of any underlying implications or restrictions of specifying None._

*Note:* apisepc contains a default resolver method, again I am not aware of whether flasgger should default to this.
https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/__init__.py#L40

**I hope this investigation helps in the resolution of the issue.**

**Comment by YJinHai** [comment]
> _我已经确定了同样的错误，虽然我无法追踪任何一个模块中的确切变化：apispec或marshmallow。_
> 
> ## 调查
> 闪光灯中的错误报告：
> 
> ```
> ../../../env36/lib64/python3.6/site-packages/flasgger/marshmallow_apispec.py:13: in <module>
>     openapi_converter = openapi.OpenAPIConverter(openapi_version='2.0')
> E   TypeError: __init__() missing 2 required positional arguments: 'schema_name_resolver' and 'spec'
> ```
> 该文件最后更新**8个月前**，得_[自54d9e77](https://github.com/rochacbruno/flasgger/commit/54d9e77877d9bd849b3f65be064a73968c5ff580) 于2018年6月29日_：[https](https://github.com/rochacbruno/flasgger/blob/master/flasgger/marshmallow_apispec.py)：[//github.com/rochacbruno/flasgger/blob/master/flasgger/marshmallow_apispec.py](https://github.com/rochacbruno/flasgger/blob/master/flasgger/marshmallow_apispec.py)
> 
> 该文件导入以下内容：
> `from apispec.ext.marshmallow import openapi`
> 
> 这导致我们：[https](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/openapi.py#L107)：[//github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/openapi.py#L107](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/openapi.py#L107)
> 在审核了提交后，似乎以下更改可能导致错误在闪光灯中：
> 
> * [marshmallow-code / apispec @ 35287af #diff-462f583a2475d6692f0826c94b8dc686](https://github.com/marshmallow-code/apispec/commit/35287af6398fb34c77f387a24b114b78320c0d57#diff-462f583a2475d6692f0826c94b8dc686)
> * [marshmallow-code / apispec @ 6f6c6b7 #diff-462f583a2475d6692f0826c94b8dc686](https://github.com/marshmallow-code/apispec/commit/6f6c6b7bfa0054228c191fa626d6c59642ed367c#diff-462f583a2475d6692f0826c94b8dc686)
> * [棉花糖代码/ apispec @ 98a9c40 #diff-462f583a2475d6692f0826c94b8dc686](https://github.com/marshmallow-code/apispec/commit/98a9c402a8208e95c86c340e49281049dda1b3c9#diff-462f583a2475d6692f0826c94b8dc686)
> 
> ## 对闪光灯的修复
> https://github.com/rochacbruno/flasgger/blob/master/flasgger/marshmallow_apispec.py#L13
> 
> ```
> openapi_converter = openapi.OpenAPIConverter(
>     openapi_version="2.0", 
>     schema_name_resolver=None, 
>     spec=None
> )
> ```
> _此更改使代码能够运行，但我不知道指定None的任何潜在影响或限制。_
> 
> _注意：_ apisepc包含一个默认的解析器方法，我不知道是否应该默认使用闪光灯。
> https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/__init__.py#L40
> 
> **我希望这项调查有助于解决问题。**


Thanks. According to your update, this error appears:
```python
  File "C:\Users\86178\PycharmProjects\restful-test\venv\lib\site-packages\flasgger\marshmallow_apispec.py", line 13, in <module>
    openapi_converter = openapi.OpenAPIConverter(openapi_version='2.0')
TypeError: __init__() missing 2 required positional arguments: 'schema_name_resolver' and 'spec'

Process finished with exit code 1

```

**Comment by georgiana-gligor** [comment]
I am also unable to do a simple `swag = Swagger(app)`. 
Windows + Python dev environment.
```toml
flasgger = "^0.9.2"
apispec = "^1.2"
marshmallow = "^2.19"
apispec_webframeworks = "^0.4.0"
```
Here's my trace:

```bash
Traceback (most recent call last):
  File "<redacted-proj-path>\__init__.py", line 4, in <module>
    from flasgger import APISpec, Schema, Swagger, fields
  File "<redacted-py-path>\pypoetry\Cache\virtualenvs\<redacted-proj-name>-py2.7\lib\site-packages\flasgger\__init__.py", line 8, in <module>
    from .base import Swagger, Flasgger, NO_SANITIZER, BR_SANITIZER, MK_SANITIZER, LazyJSONEncoder  # noqa
  File "<redacted-py-path>\pypoetry\Cache\virtualenvs\<redacted-proj-name>-py2.7\lib\site-packages\flasgger\base.py", line 37, in <module>
    from .utils import extract_definitions
  File "<redacted-py-path>\pypoetry\Cache\virtualenvs\<redacted-proj-name>-py2.7\lib\site-packages\flasgger\utils.py", line 22, in <module>
    from .marshmallow_apispec import SwaggerView
  File "<redacted-py-path>l\pypoetry\Cache\virtualenvs\<redacted-proj-name>-py2.7\lib\site-packages\flasgger\marshmallow_apispec.py", line 13, in <module>
    openapi_converter = openapi.OpenAPIConverter(openapi_version='2.0')
TypeError: __init__() takes exactly 4 arguments (2 given)
```

**Comment by masayuki038** [comment]
I am a beginner of flasgger.

I tried to fix this, but failed. I think that the above rough changes fix on a case using APISpec of flasgger like examples/apispec_example.py, but I do not know how to respond to a case without it like examples/colors_with_schema.py.

Can anyone give me advice?

**Comment by dracepj** [comment]
I am now getting...`  File "../src/flasgger/flasgger/utils.py", line 126, in get_specs
    convert_schemas(apispec_swag, apispec_definitions)
  File "../src/flasgger/flasgger/marshmallow_apispec.py", line 120, in convert_schemas
    new[k] = schema2parameters(v)
  File "../python3.6/site-packages/apispec/ext/marshmallow/openapi.py", line 490, in schema2parameters
    prop = self.resolve_schema_dict(schema)
  File "../python3.6/site-packages/apispec/ext/marshmallow/openapi.py", line 718, in resolve_schema_dict
    return self.resolve_nested_schema(schema)
  File "../python3.6/site-packages/apispec/ext/marshmallow/openapi.py", line 459, in resolve_nested_schema
    name = self.schema_name_resolver(schema_cls)
TypeError: 'NoneType' object is not callable
` 

Anyone else seeing this?

**Comment by felixonmars** [comment]
@dracepj Same here while trying to run flasgger's test suite with apispec 1.2.1

**Comment by dracepj** [comment]
I was able to get this working with the following versions...
```flasgger = "==0.9.1"
marshmallow = "*"
apispec = "==0.39.0"```

**Comment by kushan-gunasekera** [comment]
This issue is fixed now, but  still not in `pypi`. Try to install it using `pip install https://github.com/rochacbruno/flasgger/tarball/master`.
