### ISSUE TITLE
KeyError: '__file__'

### ISSUE THREAD

**Issue by messense** [rochacbruno/flasgger#80]
```
2017-04-01 10:44:17,525 INFO werkzeug._log:87    127.0.0.1 - - [01/Apr/2017 10:44:17] "GET /apispec_1.json HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/werkzeug/contrib/profiler.py", line 103, in __call__
    p.runcall(runapp)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/werkzeug/contrib/profiler.py", line 96, in runapp
    appiter = self._app(environ, catching_start_response)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flasgger/base.py", line 478, in get
    endpoint=rule.endpoint, verb=verb
  File "/usr/local/var/pyenv/versions/3.6.1/envs/brm-api/lib/python3.6/site-packages/flasgger/base.py", line 76, in _parse_docstring
    obj.__globals__['__file__']
KeyError: '__file__'
```

**Comment by messense** [comment]
0.6.1 workes fine, 0.6.2 breaks.

**Comment by messense** [comment]
Caused by https://github.com/rochacbruno/flasgger/commit/7a3db9458cbed4e031dec688e1281f777016582e

**Comment by rochacbruno** [comment]
hi tks for reporting
which example to reproduce the error? can you share example code for the app?

**Comment by rochacbruno** [comment]
this may be replaced with `inspect.getfile`

**Comment by messense** [comment]
`inspect.getfile` gets: 
```
>>> inspect.getfile(obj)
'<decorator-gen-38>'
```

The view func has a decorator applied.

**Comment by rochacbruno** [comment]
@messense I added a fix, and a test `examples/decorator_package.py` please try again ans let me know if works so I can release `0.6.3`

Thanks

**Comment by messense** [comment]
@rochacbruno It works, thanks.
