### ISSUE TITLE
Add template_file argument to initialize from yaml or json

### ISSUE THREAD

**Issue by s8sg** [rochacbruno/flasgger#88]
```sh
ENGINE ValueError('dictionary update sequence element #0 has length 1; 2 is required',)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/cheroot/server.py", line 942, in communicate
    req.respond()
  File "/Library/Python/2.7/site-packages/cheroot/server.py", line 770, in respond
    self.server.gateway(self).respond()
  File "/Library/Python/2.7/site-packages/cheroot/wsgi.py", line 94, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/Library/Python/2.7/site-packages/cherrypy/_cptree.py", line 285, in __call__
    return app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flasgger/base.py", line 148, in get
    data.update(self.template)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by rochacbruno** [comment]
What is the `template` you are passing?

**Comment by rochacbruno** [comment]
`template` must be a dict or a list of tuples. can you share yours?

**Comment by s8sg** [comment]
Thanks for the quick response. It was my bad. I was sending a swagger string. It will be nice to have a direct api to initialize Swagger() object from .yaml or .json file, if there isn't any such way

**Comment by rochacbruno** [comment]
@s8sg I like the idea, must implement `template_file` argument.

**Comment by rochacbruno** [comment]
That is implemented already https://github.com/rochacbruno/flasgger/blob/master/examples/colors_template_yaml.py

closing

**Comment by sandeepyadav1478** [comment]
Hi @rochacbruno!

I am getting following error -->  ValueError: dictionary update sequence element #0 has length 1; 2 is required
Pls check template file :>

```
swagger: '2.0'
info:
  description: 'Demo Description'
  version: 1.0.0
  title: Compliance Workload API's
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /username:
    get:
      parameters:
        - in: header
          name: X-head
          type: string
          required: true
      responses:
        200:
          description: User created
          content:
            text/plain:
              schema:
                type: string
                example: pong
```

And flask code:

```
from flask import Flask
from flasgger import Swagger
from flask_restful import Api, MethodView

app = Flask(__name__)
api = Api(app)
swagger = Swagger(app,template='check.yaml')

class UserAPI(MethodView):
    def get(self):
        return "username"

api.add_resource(UserAPI, '/username')

if __name__ == '__main__':
    app.run(debug=True)
```
